繁體中文字串更新
brevent/Brevent pull request #295
Opened 2018-04-02 12:39 UTC by tony8077616

更新紀錄：

-修正
--部分專有名詞修正
--部分專有名詞口語化翻譯

2018-04-02 12:42 UTC, liudongmiao commented
#293  呃，和这个会有冲突吧....

2018-04-02 12:48 UTC, tony8077616 commented
我來把你在 #293 的建議再修正一次好了

2018-04-02 12:48 UTC, pan93412 reviewed
感謝了，接下來就讓給你處理。

2018-04-02 14:12 UTC, tony8077616 commented
修正完畢，將改善部分重新調整
支付->購買
"支付寶"則維持其原應用程式名稱

2018-04-07 00:52 UTC, liudongmiao commented on brevent/src/main/res/values-zh-rTW/strings.xml
> +    <string name="show_donation">顯示購買</string>
统一使用 支付

2018-04-07 00:55 UTC, liudongmiao commented on brevent/src/main/res/values-zh-rTW/strings.xml
> +    <string name="brevent_appops">應用程式動作</string>
https://github.com/aosp-mirror/platform_packages_apps_settings/blob/android-8.1.0_r16/res/values-zh-rTW/strings.xml#L1678

aosp 叫 "应用程式作业"

2018-04-07 00:56 UTC, liudongmiao commented on brevent/src/main/res/values-zh-rTW/strings.xml
> +    <string name="brevent_about_translator">孟武．尼德霍格．龍\ndavid082321\npan93412</string>
如果使用你这个的话，不用加别人...我建议，你们都换个短点的名字吧...

2018-04-07 00:57 UTC, liudongmiao requested changes
统一使用 支付，其它的参照 comment

2018-04-09 13:17 UTC, tony8077616 commented
那就購買都改成支付吧

2018-04-20 04:22 UTC, closed without merging