feat(zh_TW): update zh_TW translations
brevent/Brevent pull request #607
Opened 2019-09-17 14:16 UTC by pan93412

2019-09-17 14:17 UTC, pan93412 commented
LGTM, waiting for @david082321 reviewing.

2019-09-17 14:28 UTC, david082321 commented
Great.👍

2019-09-18 23:25 UTC, liudongmiao commented on brevent/src/main/res/values-zh-rTW/strings.xml
> +    <string name="fragment_guide_welcome_message">
请不要故意调整格式，方便查看改动字词。

2019-09-18 23:26 UTC, liudongmiao requested changes

2019-09-18 23:26 UTC, liudongmiao commented on brevent/src/main/res/values-zh-rTW/strings.xml
> +    <string name="brevent_service_adb_running"> (已啟用)</string>
我不明白为啥从 中文括号 改为 英文括号。

2019-09-20 12:11 UTC, pan93412 commented on brevent/src/main/res/values-zh-rTW/strings.xml
> +    <string name="fragment_guide_welcome_message">
OK.

2019-09-20 12:17 UTC, pan93412 commented
@liudongmiao could you recheck those? thanks! :)

2019-09-21 23:20 UTC, liudongmiao approved these changes

2019-09-21 23:20 UTC, merged