Update messages
brevent/Brevent pull request #80
Opened 2017-09-04 09:16 UTC by liyufan

是用`ERROR: please open Brevent to make a new brevent.sh`还是`ERROR: please open Brevent to create a new brevent.sh`呢

2017-09-05 22:57 UTC, liudongmiao requested changes

2017-09-05 22:57 UTC, liudongmiao commented on brevent/src/main/jni/brevent.c
> +        printf("WARNING: running as root is experimental!!!\n");
代码中的，除了 typo，一律不改。

2017-09-05 22:57 UTC, liudongmiao commented on brevent/src/main/res/raw/brevent.sh
> +    echo "ERROR: please open Brevent to create a new brevent.sh" >&2
代码中的，除了 typo，一律不改。
而且，这个，基本没人能见到。
这个也不是 create 的意思，是已经存在，要重新生成。

2017-09-05 22:57 UTC, liudongmiao commented on CONTRIBUTORS.md
> +- `liyufan`: Li Yufan
那 brevent_about_translator 中你的名字也一并改了吧。

2017-09-06 00:57 UTC, liyufan commented on CONTRIBUTORS.md
> +- `liyufan`: Li Yufan
根据 [CONTRIBUTORS.md](CONTRIBUTORS.md)里面的规范，左边为翻译者想在ABOUT里面显示的名字；右边为翻译者的GitHub profile里面的Name。

2017-09-06 00:59 UTC, liyufan commented on brevent/src/main/res/raw/brevent.sh
> +    echo "ERROR: please open Brevent to create a new brevent.sh" >&2
那`<string name="unsupported_path">(Error: cannot create brevent.sh)</string>`是用create还是make呢

2017-09-06 04:10 UTC, liudongmiao commented on CONTRIBUTORS.md
> +- `liyufan`: Li Yufan
一起改了吧..

2017-09-06 04:11 UTC, liudongmiao commented on brevent/src/main/res/raw/brevent.sh
> +    echo "ERROR: please open Brevent to create a new brevent.sh" >&2
这种，基本不可能的错误，其实无所谓。不改。

2017-09-06 04:35 UTC, liyufan commented
已完成所要求的更改。

2017-09-06 09:19 UTC, liudongmiao approved these changes

2017-09-08 12:34 UTC, merged

2017-09-08 12:50 UTC, liyufan commented
@samforo please refer commit [`cf3bed2`](https://github.com/brevent/Brevent/commit/cf3bed27a3dbdfb1dca2bacd946409ea5f052874) to continue your translation.

2017-09-08 13:04 UTC, samforo commented
Hi, this weekend I'm going to finish the pending translations. If I have time today, I'll get on with it.

A greeting

2017-09-11 09:52 UTC, samforo commented
All changes have been made. You can merge this pull request.

Thanks